### ISSUE TITLE
设置时遇到问题

### ISSUE THREAD

**Issue by throwthatbrick** [gnepnuy/sandwich-robot#2]
你认为你可以写一个关于如何设置的快速教程吗？我在尝试运行 bnc-find.js 时遇到错误

**Comment by throwthatbrick** [comment]
我让它工作了，但新版本没有向合同发送任何内容。你能帮我吗？ <3

**Comment by throwthatbrick** [comment]
看起来blocknative api非常有限。您可能可以从 https://github.com/libevm/subway 获取一些代码，这样您就不会被限制为每天 1,000 笔交易。

**Comment by tianji6666** [comment]
how to make it work?

**Comment by tianji6666** [comment]
Can u teach me how to run the bot ? :)

**Comment by tianji6666** [comment]
How did u make it work?

**Comment by throwthatbrick** [comment]
It doesn't really work, I just got it to scan.

**Comment by tianji6666** [comment]
> It doesn't really work, I just got it to scan.

so,did u seccess?

**Comment by tianji6666** [comment]
what's your sepecific progresses?

**Comment by tianji6666** [comment]
first , npx hardhat compile.And then?

> It doesn't really work, I just got it to scan.

**Comment by tianji6666** [comment]
did u figure it out?
